name: Build Python Package

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      # with:
      #   python-version: '3.x' # Specify your desired Python version, e.g., '3.9', '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel cibuildwheel # Install tools for building distributions
        # If your project has specific dependencies, install them here
        # pip install -r requirements.txt

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl
